import Head from "next/head";
import MouseTracker from "~/components/MouseTracker"
import MousePredictor from "~/components/MousePredictor";

const TRAIN = false;

export default function Home() {
  return (
    <>
      <Head>
        <title>Mouse Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {TRAIN ?  <MouseTracker /> : <MousePredictor /> }
      </main>
    </>
  );
}
